---
format: html
---

## **`r fontawesome::fa("laptop-code", fill = "#5A5A5A", a11y = "sem")`** How do I get better / gain confidence in creating data visualizations?

Creating beautiful and effective data visualizations is a skill that gets better with practice -- give [#tidytuesday](https://github.com/rfordatascience/tidytuesday) a whirl, try recreating existing data visualizations (e.g. participate in the [W.E.B. Du Bois Visualization Challenge](https://medium.com/nightingale/recreating-w-e-b-du-boiss-data-portraits-87dd36096f34)[^1]), enter a [Kaggle competition](https://www.kaggle.com/competitions), take a deep dive into aRtistry (check out [Ijeamaka Anyene's](https://ijeamaka-anyene.netlify.app/) amazing talk on creating radial visualizations with `ggplot2` - [slides](https://ijeamakaanyene.github.io/aRt_ggplot/index.html#1) & [recording](https://www.youtube.com/watch?v=h0i6KAahLY8&ab_channel=R-LadiesGlobal)), or simply start playing around with data that means something to you.

[^1]: [W.E.B. Du Bois](https://en.wikipedia.org/wiki/W._E._B._Du_Bois) (February 23, 1868 – August 27, 1963) was an African American writer, scholar and activist. Among his many achievements, Du Bois was the first African American to earn a PhD from Harvard University, shaped the field of sociology as we know it today, and helped found the [National Association for the Advancement of Colored Peopple (NAACP)](https://en.wikipedia.org/wiki/NAACP). 

    In 1900, Du Bois designed and curated [The Exhibit of American Negroes](https://en.wikipedia.org/wiki/The_Exhibit_of_American_Negroes) for the [Exposition Universelle (Paris Exposition)](https://en.wikipedia.org/wiki/Exposition_Universelle_(1900)) in Paris. He used photographs and data visualizations/infographics to commemorate the lives of African Americans at the turn of the century and challenge the racist caricatures and stereotypes of the day.

    The [W.E.B. Du Bois challenge](https://nightingaledvs.com/the-dubois-challenge/), started in 2021 by [Anthony Starks](https://twitter.com/ajstarks), [Allen Hillery](https://twitter.com/AlDatavizguy/status/1358454676497313792?s=20), and [Sekou Tyler](https://twitter.com/sqlsekou/status/1360281040657522689?s=20), challenges people recreate Du Bois's visualizations from the 1900 Paris Exposition using modern tools (Tableau, R, ggplot2, Stata, PowerBI, decksh, etc). Celebrate Black History month by participating in the challenge and search [#DuBoisChallenge](https://twitter.com/search?q=%23DuBoisChallenge&src=typed_query) on Twitter to see lots of incredible recreations!

## **`r fontawesome::fa("book-open-reader", fill = "#5A5A5A", a11y = "sem")`** Review & Resources

Take a look back at [Allison Horst's](https://allisonhorst.github.io/) data viz lectures and labs from EDS 221 for a `{ggplot2}` review, practice, and a reminder about important considerations for making responsible data visualizations:

- [**Lecture 15:** The (layered) grammar of graphics & data viz considerations](https://docs.google.com/presentation/d/e/2PACX-1vSpUdai7BTXprh3dwSNBpJymNGUIOFhEgQn5XbQWZhWy8EpUyd64Lem08YK_kc6tP0iyoJ5wRAVvSYe/pub?start=false&loop=false&delayms=3000&slide=id.p)
-[**Lecture 16:** Data exploration and visualization continued](https://docs.google.com/presentation/d/e/2PACX-1vR1QB0S3AfBfdJZ1nnhUw2iKSxV83GDc5l9BYPC6yQhxBdnzRpAAZ2lh7QWhX4kY65Uf_q0yK9FtHmW/pub?start=false&loop=false&delayms=3000&slide=id.p)
- [**Lab:** Customized Data Visualization in `ggplot2`](https://allisonhorst.github.io/eds221-day8-comp/data_viz.html)

Or another excellent workshop by Allison Horst, presented to the Southern California Coastal Water Research Project (SCCWRP):

- [Data visualization: Communicating data with responsible, clear, and engaging visualizations](https://docs.google.com/presentation/d/1EA_PfTiSXh8J0JH03d1pcA6luVJeN2oUGozxhZoiydQ/edit#slide=id.g605a49e43e_0_58)

There are lots of other great data viz resources out there as well. Check out:

- [A ggplot2 Tutorial for Beautiful Plotting in R
](https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/), by [Cédric Scherer](https://www.cedricscherer.com/): a super comprehensive `{ggplot2}` tutorial that also includes a bunch of awesome interactive data viz examples (leveraging existing JavaScript libraries)
- [Beautifully Annotated: Enhancing your ggplots with Text](https://www.cararthompson.com/talks/rl-cambridge-beautifully-annotated/), by [Cara Thompson](https://www.cararthompson.com/index.html): blogpost + workshop slides; honestly one of the best tutorials on annotating ggplots that I've ever come across 
- Search [#tidytuesday](https://twitter.com/search?q=%23tidytuesday&src=typed_query) on Twitter to explore an endless supply of incredibly creative data visualizations -- *this is seriously such an great way to learn new plotting tools/approaches and find inspiration for your next plot!*
- [ggplot extensions](https://exts.ggplot2.tidyverse.org/): explore registered `ggplot2` extensions (though this list is not exhaustive)

There are a number of great online books as well, including: 

- [`ggplot2` Cookbook](http://www.cookbook-r.com/Graphs/), by [Winston Chang](https://github.com/wch)
- [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/), by [Claus O. Wilke](https://clauswilke.com/)
- [Data Visualization: A Practical Introduction](https://socviz.co/index.html#preface), by [Kieran Healy](https://kieranhealy.org/)